## En este apartado utilizaremos los datos ya limpios que obtuvimos

In [1]:
# Importo las librerias a utilizar en este proceso de visualizacion de datos
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# Leo el archivo con los datos ya limpios
df = pd.read_csv("Datos Limpios Salarios Mexico.csv", sep=";", encoding="utf-8")
df = df.drop(columns=["Unnamed: 0"])
df.head()

,Entidad Federativa,Sexo,2005 Trimestre I,2005 Trimestre II,2005 Trimestre III,2005 Trimestre IV,2006 Trimestre I,2006 Trimestre II,2006 Trimestre III,2006 Trimestre IV,...,2021 Trimestre III,2021 Trimestre IV,2022 Trimestre I,2022 Trimestre II,2022 Trimestre III,2022 Trimestre IV,2023 Trimestre I,2023 Trimestre II,2023 Trimestre III,2023 Trimestre IV
0,Aguascalientes,Hombres,7956.986146,8049.330920,8228.385315,8162.127084,7790.181800,8489.410853,8439.755319,7987.732875,...,7912.679217,7648.109072,8323.847492,8379.504958,7562.818107,7660.378085,7975.511519,8083.148186,7762.185006,8059.590490
1,Aguascalientes,Mujeres,5738.093081,6014.697008,6458.982780,5927.876338,6003.173507,6218.697676,6159.854554,5509.048836,...,6006.032279,5777.487228,6380.068829,6031.197480,6058.736912,5916.811515,6384.733535,6027.326483,6232.155533,6326.378096
2,Baja California,Hombres,11121.332440,11554.325486,11719.864926,11799.271502,11943.729951,12352.620810,12014.600893,11642.132797,...,9697.533510,9531.697427,10653.652687,10513.316764,10406.833206,10520.641082,10930.090052,11024.219651,11466.613763,11150.548745
3,Baja California,Mujeres,8681.546303,8730.942158,9139.675116,8970.430082,9226.693396,9189.111038,9259.457728,8729.694057,...,8138.362005,7577.269433,8508.610418,8212.507327,8728.911717,8236.631117,8826.823642,9385.479492,9145.234686,8976.979799
4,Baja California Sur,Hombres,10687.529000,10994.352958,11123.709717,11140.542736,10634.309800,12069.135270,11646.069305,12697.486293,...,11714.217021,11405.967836,10886.453929,11315.246464,11456.636535,10887.651395,11517.980555,11974.998000,12022.313625,11809.187075